name: flutter_wind_surf_demo
description: "A Flutter demo project for WindSurf IDE."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.1
  auto_route: ^7.8.4
  sqflite: ^2.3.2
  path: ^1.8.3
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  flutter_lints: ^3.0.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true
flavors:
  dev:
    applicationIdSuffix: .dev
  staging:
    applicationIdSuffix: .stage
  prod:
    applicationIdSuffix: .prod
